server:
  port: 8100

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/bank_microservice
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always      #for initialization of schema.sql

logging:
  level:
    web: DEBUG