server:
  port: 8071

spring:
  application:
  name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ruuunardo/udemy-microservice-configrepo"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  metrics:
    tag:
      application:${spring.application.name}

encrypt:
  key: "45dfhji6789hgf765fgffgd"



