server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "user"
    password: "password"
  cloud:
    config:
      server:
#        native:
#          search-location: "file:///C://Users//Ruby Joy Nardo//Documents//01-Java//configserver"
#          search-location: "classpath:/config"
        git:
          uri: "https://github.com/ruuunardo/udemy-microservice-configrepo"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45dfhji6789hgf765fgffgd"



